name: samal
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.5.0
  firebase_storage: ^11.0.15
  firebase_messaging: ^14.2.6
  firebase_core: ^2.7.1
  cloud_firestore: ^4.6.0
  fluttertoast: ^8.0.8
  local_auth: ^2.1.6
  flutter_secure_storage: ^8.0.0
  percent_indicator: ^4.0.1
  file_picker: ^5.3.0
  flutter_charts: ^0.5.1
  awesome_card: ^1.1.7
  syncfusion_flutter_pdfviewer: ^19.2.51-beta
  encrypt: ^5.0.1
  http: ^0.13.6
  pointycastle: ^3.7.3
  google_fonts: ^4.0.4
  syncfusion_flutter_charts: ^19.1.56
  liquid_progress_indicator: ^0.4.0
  email_otp: ^1.0.4
  image_picker: ^0.8.7+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
